### ISSUE TITLE
Feature: The UI should indicate the total number of open orders for the asset, amount of the asset committed to orders, and amount of algos in orders.

### ISSUE THREAD

**Issue by atrefonas** [algodex/trading-bot#193]
# ℹ Overview

Maybe in the same box showing the available balance? @stephclarkga 

This doesn't need to be done in the first release but would be good to display I think.

**Comment by stephclarkga** [comment]
I think the best thing to do here is to make an additional chart that shows the current open orders. Hopefully there's not too much of a lag in updating it but we can mention that it can be slightly off as new orders are updated. I think this is much more useful than just saying the number of open orders since it allows users to visualize better. I don't think there's room to show the USD and ALGO prices at once but we can do something similar to the rewards app and have a toggle to switch between ALGO and USD values in the chart. This takes some screen space from logs taking up that whole right side of the screen especially with high order numbers (might be best to make it scrollable when over 4 or 5 orders on each side) but I don't think that's a problem on most screen sizes. (obviously not designing for mobile at all right now - we would likely have to make several tabs like we have with Algodex)

<img width="1440" alt="Open Orders Chart" src="https://user-images.githubusercontent.com/59464107/207092770-5b499814-b5a2-4b0e-9ce4-44c502681c10.png">
