### ISSUE TITLE
Feature: Highlight the alert message if the users are not qualified for the rewards

### ISSUE THREAD

**Issue by hasyminh** [algodex/trading-bot#203]
Maybe we use red color for "DO NOT" if the users fail to meet the standards..
![image](https://user-images.githubusercontent.com/39449399/204897692-65ec8dfd-5b3f-45fe-b9b0-347959c823ab.png)

**Comment by treasurechic** [comment]
@hasyminh, is red not harsh?🤔.....do we need to highlight it with another color🤔 since we have it in capitals?

@stephclarkga , pls what do you think about using red for "DO NOT"

**Comment by hasyminh** [comment]
I just thought of red for regular alerts. Yes, we can use other colors.

**Comment by stephclarkga** [comment]
I would not make "DO NOT" red - it would be too much especially since the next sentence (the link) is in green. Underlining it is fine if you think it needs more of a callout.

@treasurechic The icons should also be different if the settings do not qualify - It should be the ! in the circle instead of the checkmark. Should be the same icon as used in the Rewards app but I can drop it here if needed.

**Comment by hasyminh** [comment]
Btw, there's a typo in Read about Rewards _**Calcuations**_. It's Calculations
